version: '2'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: trumpet2012/network-trace:latest
    expose:
      - "8000"
    volumes:
      - web-code:/code

  nginx:
    build:
      context: .
      dockerfile: Nginx.Dockerfile
    image: trumpet2012/network-trace-nginx:latest
    depends_on:
      - web
    ports:
      - "80"
    volumes_from:
      - web

  web-static:
    image: trumpet2012/network-trace:latest
    entrypoint: python manage.py
    command: collectstatic --no-input
    depends_on:
      - web
    volumes_from:
      - web

  web-migrations:
    image: trumpet2012/network-trace:latest
    entrypoint: python manage.py
    command: migrate --no-input
    depends_on:
      - web
    volumes_from:
      - web
