# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
