# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0002_auto_20160325_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
